"""Command Line Interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/config.ipynb.

# %% auto 0
__all__ = ['APP_NAME', 'CONFIG_DIR', 'CONFIG_FILE', 'load_config', 'save_config', 'get_setting', 'set_setting']

# %% ../nbs/API/config.ipynb 3
import json
from pathlib import Path
from appdirs import user_config_dir
from fastcore.test import *

# %% ../nbs/API/config.ipynb 5
APP_NAME = "markdown_sync"
CONFIG_DIR = Path(user_config_dir(APP_NAME))
CONFIG_FILE = CONFIG_DIR / "config.json"

def load_config():
    """Load config, creating default if it doesn't exist"""
    if not CONFIG_FILE.exists():
        return {}
    
    with open(CONFIG_FILE) as f:
        return json.load(f)

def save_config(config):
    """Save config to file"""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config, f, indent=2)



# %% ../nbs/API/config.ipynb 13
def get_setting(key, default=None):
    """Get a specific setting"""
    config = load_config()
    return config.get(key, default)

def set_setting(key, value):
    """Set a specific setting"""
    config = load_config()
    config[key] = value
    save_config(config)
